version: '3'

services:
  media-server:
    image:  ${repo_pre}dips/media-server${tag}
    restart: always
    ports:
      - 80:5000
    volumes:
      - "./DevDays2018:/app/wwwroot/Conference/DevDays2018"