version: '3'

services:
  cache-populator:
    image: ${repo_pre}dips/cache-populator${populate_tag}
    restart: always
    ports:
      - 1337
    depends_on:
      - media-server
  media-server:
    image:  ${repo_pre}dips/media-server${tag}
    restart: always
    ports:
      - 80:5000
    volumes:
      - "./DevDays2018:/app/wwwroot/Conference/DevDays2018"
      - "./Interesting:/app/wwwroot/Conference/Interesting"
      - "./OptimusInteresting:/app/wwwroot/Conference/OptimusInteresting"